version: 0.2 

phases:
 install:
   commands: 
     - echo "Nothing to install in this simple build."

  pre_build:
   commands:
     - echo "preparing for build."

  build:
   commands: 
     - echo "Building project...(in this case, no build is needed for static HTML)."


  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files: 
   - 'index.html'           
